name: build-and-publish

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install build
      - name: Lint with flake8
        run: |
          flake8 plugin --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1