name: example

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install xdist
        run: |
          pip install pytest-xdist

      - name: Install plugin
        run: |
          pip install .

      - name: Run tests
        run: |
          python -m pytest --ctrf $REPORT -m 'not smoke' -n auto
        env:
          REPORT: 'test-results/report.json'

      - name: Generate Pretty Report
        run: |
          npx github-actions-ctrf test-results/report.json